language: python
python:
  - "3.4.2"
  - "3.4.3"
  - "3.5"
install:
  pip install -U setuptools coveralls
before_script:
- ulimit -c unlimited -S       # enable core dumps
script:
  ( cmdpid=$BASHPID; (sleep 300; kill -SIGABRT $cmdpid) & PYTHONFAULTHANDLER=true coverage run --source=RPiNWR ./setup.py test )
after_success:
  coveralls
after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
