language: python
python:
  - "3.4.2"
  - "3.4.3"
  - "3.5"
install: 
  pip install -U setuptools coveralls
# command to install dependencies
script:
  coverage run --source=RPiNWR ./setup.py test
after_success:
  coveralls
